name: fake_image_picker_example
description: Example usage of the fake_image_picker package.
publish_to: 'none'

environment:
  sdk: ^3.10.0
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.2.2

dev_dependencies:
  fake_image_picker:
    path: ../
  flutter_test:
    sdk: flutter
